### PR TITLE
Angular 15

### LINKED ISSUE #18: Upgrade to Angular 15
Hello, I was trying to be helpful and upgrade this repo to Angular 15, alas, the code won't compile for me after the upgrade:
```

> ng build
One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output is not supported by the Angular CLI.
Ignored browsers: kaios 2.5, op_mini all
⠋ Generating browser application bundles (phase: setup)...    TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://angular.io/guide/build#configuring-browser-compatibility
    NOTE: You can set the "target" to "ES2022" in the project's tsconfig to remove this warning.
✔ Browser application bundle generation complete.

./src/app/app.module.ts:5:0-49 - Error: Module not found: Error: Can't resolve 'ngx-joystick' in 'C:\git\ngx-joystick\src\app'

Error: src/app/app.component.html:8:9 - error NG8001: 'ngx-joystick' is not a known element:
1. If 'ngx-joystick' is an Angular component, then verify that it is part of this module.
2. If 'ngx-joystick' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

  8         <ngx-joystick #staticJoystic
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  9                         [options]="staticOptions"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 15                         (plainLeft)="onPlainLeftStatic($event)"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 16                         (plainRight)="onPlainRightStatic($event)"></ngx-joystick>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:9:25 - error NG8002: Can't bind to 'options' since it isn't a known property of 'ngx-joystick'.
1. If 'ngx-joystick' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ngx-joystick' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

9                         [options]="staticOptions"
                          ~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:20:57 - error NG8004: No pipe found with name 'number'.

20             <div>xPos: {{ staticOutputData.position.x | number:'3.2-2'}}</div>
                                                           ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:21:57 - error NG8004: No pipe found with name 'number'.

21             <div>yPos: {{ staticOutputData.position.y | number:'3.2-2'}}</div>
                                                           ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:25:72 - error NG8004: No pipe found with name 'number'.

25         <div>frontXPos: {{ staticOutputData.instance.frontPosition.x | number:'2.5-5'}}</div>
                                                                          ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:26:72 - error NG8004: No pipe found with name 'number'.

26         <div>frontYPos: {{ staticOutputData.instance.frontPosition.y | number:'2.5-5'}}</div>
                                                                          ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:27:49 - error NG8004: No pipe found with name 'number'.

27         <div>force: {{ staticOutputData.force | number:'1.5-5'}}</div>
                                                   ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:28:60 - error NG8004: No pipe found with name 'number'.

28         <div>angle-deg: {{ staticOutputData.angle.degree | number:'3.5-5'}}</div>
                                                              ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:40:9 - error NG8001: 'ngx-joystick' is not a known element:
1. If 'ngx-joystick' is an Angular component, then verify that it is part of this module.
2. If 'ngx-joystick' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

40         <ngx-joystick #semiJoystick [options]="semiOptions" (move)="onMoveSemi($event)"></ngx-joystick>
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:40:37 - error NG8002: Can't bind to 'options' since it isn't a known property of 'ngx-joystick'.
1. If 'ngx-joystick' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ngx-joystick' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

40         <ngx-joystick #semiJoystick [options]="semiOptions" (move)="onMoveSemi($event)"></ngx-joystick>
                                       ~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:44:55 - error NG8004: No pipe found with name 'number'.

44             <div>xPos: {{ semiOutputData.position.x | number:'3.2-2' }}</div>
                                                         ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:45:55 - error NG8004: No pipe found with name 'number'.

45             <div>yPos: {{ semiOutputData.position.y | number:'3.2-2' }}</div>
                                                         ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:47:70 - error NG8004: No pipe found with name 'number'.

47         <div>frontXPos: {{ semiOutputData.instance.frontPosition.x | number:'2.5-5'}}</div>
                                                                        ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:48:70 - error NG8004: No pipe found with name 'number'.

48         <div>frontYPos: {{ semiOutputData.instance.frontPosition.y | number:'2.5-5'}}</div>
                                                                        ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:62:9 - error NG8001: 'ngx-joystick' is not a known element:
1. If 'ngx-joystick' is an Angular component, then verify that it is part of this module.
2. If 'ngx-joystick' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

62         <ngx-joystick #dynamicJoystick [options]="dynamicOptions" (move)="onMoveDynamic($event)"></ngx-joystick>
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:62:40 - error NG8002: Can't bind to 'options' since it isn't a known property of 'ngx-joystick'.
1. If 'ngx-joystick' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ngx-joystick' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

62         <ngx-joystick #dynamicJoystick [options]="dynamicOptions" (move)="onMoveDynamic($event)"></ngx-joystick>
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:66:58 - error NG8004: No pipe found with name 'number'.

66             <div>xPos: {{ dynamicOutputData.position.x | number:'3.2-2'}}</div>
                                                            ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:67:58 - error NG8004: No pipe found with name 'number'.

67             <div>yPos: {{ dynamicOutputData.position.y | number:'3.2-2'}}</div>
                                                            ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:69:73 - error NG8004: No pipe found with name 'number'.

69         <div>frontXPos: {{ dynamicOutputData.instance.frontPosition.x | number:'2.5-5'}}</div>
                                                                           ~~~~~~

  src/app/app.component.ts:7:16
    7   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.


Error: src/app/app.component.html:70:73 - error NG8004: No pipe found with name 'number'.

70         <div>frontYPos: {{ dynamicOutputData.instance.frontPosition.y | number:'2.5-5'}}</div>
                                                                           ~~~~~~
2 import { JoystickEvent, NgxJoystickComponent } from 'ngx-joystick';
                                                      ~~~~~~~~~~~~~~


Error: src/app/app.module.ts:5:35 - error TS2307: Cannot find module 'ngx-joystick' or its corresponding type declarations.

5 import { NgxJoystickModule } from 'ngx-joystick';
                                    ~~~~~~~~~~~~~~


Error: src/app/app.module.ts:11:12 - error NG1010: Value
```

do you have any plans to update the repository?

### PR DESCRIPTION
**Pull request by wweitzel**
Add support for Angular 15

Closes https://github.com/wweitzel/ngx-joystick/issues/18

### CODE REVIEW

**Comment by ruslanss** [comment]
good work, thanks! BTW, did you mean to lock it to v15.2.1+ ? As in it wouldn't work with v15.0-15.2.0, is that intentional?

**Comment by wweitzel** [comment]
To be honest I didn't really think about that. I just ran the update command `ng update @angular/core@15 @angular/cli@15` and went with whatever changes it made.

But you're right, we should probably change it to be `>15.0.0`. Good point.
